<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <IsDuckovMod>true</IsDuckovMod>
    <Nullable>enable</Nullable>
    <Version>1.10.2</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DuckovCoreAPI-ff7adf30876bfbe12883a7f021a147f98311984f\DuckovCoreAPI.csproj" Private="false" />
  </ItemGroup>
</Project>
